### ISSUE TITLE
No password created for root

### ISSUE THREAD

**Issue by AlexVallat** [pepa65/lmdescrypt#2]
Unless I'm doing something wrong, the resulting install of LMDE 2 (lmde-2-201503-mate-64bit) has not set a password for root. This, in turn, means that lots of stuff doesn't work, not least the Software Manager. It prompts for a password, but no password will satisfy it. `sudo passwd --status` returns `root L 04/06/2015 0 99999 7 -1`. Setting a password for root using `sudo passwd` allows the software manager (and other stuff) to work.

**Comment by pepa65** [comment]
Thanks for reporting this. If this is not working, it's a bug in the distribution. LMDE is supposed to work without a password set for root.

I've just verified from a new install (exactly the same version) that the software manager accepts the password for the sudo/first user account. Not sure why it doesn't work at yours... What else is not working?? The one thing I found not working without a root password is Administration/Login Window (the other entries under Administration seem to work with the sudo password).

In the past I have encountered situations on Debian-based systems with a sudo setup where only a root password was accepted. Indeed, the work-around in those cases would be to set a root password. You could try to file a bug as well.

I am no longer using LMDE myself, unfortunately it is not well supported...

**Comment by pepa65** [comment]
The standard installer for LMDE also doesn't set a password for root. This issue of not implementing sudo properly should be fixed "upstream" in my opinion. Luckily there is a workaround for those that like a separate root account, and for people that want a correct working sudo, they can modify the default for gksu by: `gconftool-2 --set /apps/gksu/sudo-mode --type bool true`

**Comment by AlexVallat** [comment]
That's not my experience. The LMDE 2 installer sets the root password to be the same as the user password. I don't know if you are using a different installer to me, but the lmde-2-201503-mate-64bit.iso live environment desktop shortcut "Install Linux Mint" behaves like this. In the User Guide PDF for Linux Mint it also states: 

> Note: By default, your “root” password is the same as the password you chose during the
> installation. If you do not know what this means, then don't worry about it.

Admittedly this is not specifically for the LMDE version, but it is indicative.

When I run a clean install in a VM, the result of `sudo passwd --status` is `root P 02/19/2016 0 99999 7 -1`

**Comment by pepa65** [comment]
Alright, I must have been wrong then. I was going to add the gksudo fix (which I expect should work as well), but if it's in the handbook, I should just set the root passwd then. Thanks for enlightening me!

**Comment by AlexVallat** [comment]
That's great! Your script was a huge help getting a working LMDE2 up and running for me, thanks. It was just this one little step to have the software manager working too, which is why I thought it worth mentioning.

**Comment by pepa65** [comment]
OK, think this is fixed, and improved things overall.
