### ISSUE TITLE
Could you add more info on UEFI setup?

### ISSUE THREAD

**Issue by mc0e** [pepa65/lmdescrypt#3]
I'd like to install LMDE 2 using lmdescrypt on a UEFI/GPT partitioned disk with no boot partition.

I gather you support that, but it's not all that clear how.  Could you include instructions as you have for installing with BIOS/MBR?

I'm guessing that the partition layout from https://blog.heckel.xyz/2017/05/28/creating-a-bios-gpt-and-uefi-gpt-grub-bootable-linux-system/ should be about right, though I've increased the size of the EFI System partition according to your statement that it should be at least 260MB.

    sgdisk --clear \
      --new 1::+1M --typecode=1:ef02 --change-name=1:'BIOS boot partition' \
      --new 2::+300M --typecode=2:ef00 --change-name=2:'EFI System' \
      --new 3::-0 --typecode=3:8300 --change-name=3:'Linux root filesystem' \
      /dev/sda

Seems to be working (posting before reboot)... fingers crossed.

**Comment by mc0e** [comment]
Nope, not bootable.  Gives me a near-blank screen (flashing undescore in upper left) for a bit, then returns me to boot disk selection screen.

**Comment by pepa65** [comment]
I could add some instruction for this, if you can confirm this works for you (all as `root`):
```
# Formatting the disk with partition 1 as EFI partition and 2 as encrypted one
# Change 'crypt_part=/dev/sda2' in lmdescrypt accordingly!
gdisk /dev/sda
o [Enter]
y [Enter]
n [Enter]
[Enter]
[Enter]
+260M [Enter]
ef00 [Enter]
n [Enter]
[Enter]
[Enter]
[Enter]
[Enter]
w [Enter]
y [Enter]
# Format the EFI partition
mkfs.vfat /dev/sda1
```
And then run it as usual like `source lmdescrypt`

**Comment by mc0e** [comment]
Yes, that partitioning configuration works.  The BIOS boot partition in my sgdisk command is unnecessary.  I do prefer the sgdisk non-interactive syntax to the way you explain the interactive version though.

I think I might have missed the `mkfs.vfat` command earlier.  Also, I found out from https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X220#Boot_fails_.28UEFI.2FGPT.29 that my Lenovo Thinkpad X220 is particular about the name of the `.efi` file.  Copying that into the right place was the last piece of the puzzle.  My system is now working.

Thankyou

**Comment by pepa65** [comment]
I agree with you that for this partitioning the interactive instructions are getting out of hand... The `sgdisk` command is much neater, more compact and more informative.

Having a proper EFI partition that is VFAT formatted is important. I could add a more explicit configuration option for that, but for multiboot systems the EFI partition is already there, and my focus is especially on the volumes in the encrypted partition.

What is the name of the `.efi` file that your thinkpad requires??

**Comment by mc0e** [comment]
I copied `EFI/linuxmint/grubx64.efi` to `EFI/boot/bootx64.efi`.

Various versions of the capitalisation are reported.  I was a bit concerned about that, because I saw some syslog messages about utf-8 being inappropriate due to causing case sensitivity in a FAT file system.  Doesn't seem to have been an issue though.

Andrew

-----Original Message-----

**Comment by pepa65** [comment]
Thanks, if there is no pre-existing `EFI/boot/bootx64.efi` I will copy it automatically in the script.
I am reviewing this whole partition checking, and I am changing to `sgdisk` as much as possible.

**Comment by pepa65** [comment]
I made a number of improvements to the script thanks to your input.
